version: '3.9'

services:
  php:
    container_name: php
    build: ./php
    depends_on: 
      - database
    volumes:
      - ./src:/app
    environment:
      MYSQL_HOST: "$MYSQL_HOST"
      MYSQL_DBNAME: "$MYSQL_DBNAME"
      MYSQL_USER: "$MYSQL_USER"
      MYSQL_PASSWORD: "$MYSQL_ROOT_PASSWORD"
    restart: unless-stopped
    ports:
      - ${PHP_PORT}:80
    networks:
      - appnetwork

  database:
    container_name: database
    build: 
      context: ./database
      args:
        MYSQL_DBNAME: "$MYSQL_DBNAME"
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
    networks:
      - appnetwork
networks:
  appnetwork: